### ISSUE TITLE
jest watcher isn't watching interface files

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-loader#23]
I.e. `.rei`/`.mli` files. Is this just a configuration issue?

**Comment by rrdelaney** [comment]
I don't know how possible it is to get Jest to watch interface files because they aren't direct dependencies from JS, I need to do some more research. In Webpack world, we add a contextual dependency: https://github.com/reasonml-community/bs-loader/blob/6808b024b5efaa659a2e656f3ff7251c16bdeb66/index.js#L94

We should see if Jest has something similar.

**Comment by rrdelaney** [comment]
Closing as a wontfix
